// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZIQ1-VifWx07Wz3I1Wwf4Y19k59eOWP0',
    appId: '1:322996576044:web:29bc9d2e28ba1639e1d689',
    messagingSenderId: '322996576044',
    projectId: 'souga-5fdb3',
    authDomain: 'souga-5fdb3.firebaseapp.com',
    storageBucket: 'souga-5fdb3.firebasestorage.app',
    measurementId: 'G-6HJC8FRJM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_o_b54dLTm6j6_M7v3bwbbMhN7EjB0k',
    appId: '1:322996576044:android:62b42471e0e9e401e1d689',
    messagingSenderId: '322996576044',
    projectId: 'souga-5fdb3',
    storageBucket: 'souga-5fdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzKKGMk982tq_5jvTGWTNK5rXuFp5x5ms',
    appId: '1:322996576044:ios:1f26509fc8244c16e1d689',
    messagingSenderId: '322996576044',
    projectId: 'souga-5fdb3',
    storageBucket: 'souga-5fdb3.firebasestorage.app',
    iosBundleId: 'com.souga.souga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzKKGMk982tq_5jvTGWTNK5rXuFp5x5ms',
    appId: '1:322996576044:ios:1f26509fc8244c16e1d689',
    messagingSenderId: '322996576044',
    projectId: 'souga-5fdb3',
    storageBucket: 'souga-5fdb3.firebasestorage.app',
    iosBundleId: 'com.souga.souga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZIQ1-VifWx07Wz3I1Wwf4Y19k59eOWP0',
    appId: '1:322996576044:web:d2377ffe2a6c2a37e1d689',
    messagingSenderId: '322996576044',
    projectId: 'souga-5fdb3',
    authDomain: 'souga-5fdb3.firebaseapp.com',
    storageBucket: 'souga-5fdb3.firebasestorage.app',
    measurementId: 'G-YTKKRCXV05',
  );
}
